name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
                                              
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set working directory
      run: cd ./

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:prod
      
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SOURCE: "dist/angular-17-crud-example/"
        REMOTE_HOST: "100.28.127.93"
        REMOTE_USER: "ubuntu"
        TARGET: "/var/www/html/angular-demo/"
