name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
                                              
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set working directory
      run: cd ./

    - name: Install dependencies
      run: pwd & npm install

    - name: Build
      run: npm run build
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./dist/angular-17-crud/browser/*
        remote_path: /var/www/html/angular-demo/
        remote_host: 100.28.127.93
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Set ownership on remote server
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        # Create known_hosts file if it doesn't exist
        #sudo mkdir -p /home/runner/.ssh
        #sudo touch /home/runner/.ssh/known_hosts
          
        # Clear old key from known_hosts
        #ssh-keygen -R 100.28.127.93 >> /home/runner/.ssh/known_hosts

        # Run the SSH command
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@100.28.127.93 \
        "sudo chown -R ubuntu:www-data /var/www/html/angular-demo/ && chmod 777 -R /var/www/html/angular-demo/"          
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        IP_SERVER: ${{ secrets.IP_SERVER}}
